server:
  port: ${SERVER_PORT:8083}
  servlet:
    application-display-name:
    context-path: /api
  # Server configuration
  netty:
    connection-timeout: 20000
    idle-timeout: 60s
springdoc:
  swagger-ui:
    path: /swagger-ui.html

