spring:
  temporal:
    namespace: abb-bank
    connection:
      target: 127.0.0.1:7233
    workersAutoDiscovery:
      packages:
        - az.abb.product
    workers:
      - name: product-info-worker
        task-queue: product-info-task-queue-local
      - name: customer-products-worker
        task-queue: customer-products-task-queue-local
      - name: product-restriction-worker
        task-queue: product-restriction-task-queue