spring:
  config:
    import:
      - classpath:properties/application-common.yml
      - classpath:properties/application-logging.yml
      - classpath:properties/application-management.yml
      - classpath:properties/application-server.yml
      - classpath:properties/application-temporal.yml
      - classpath:properties/integration/application-integration.yml
